apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-akka-cluster
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example-akka-cluster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-akka-cluster
    spec:
      containers:
      - image: davarski/example-akka-cluster-k8s:1.0
        imagePullPolicy: IfNotPresent
        name: example-akka-cluster
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        - name: remoting
          containerPort: 2551
        - name: api
          containerPort: 8080
        - name: management
          containerPort: 8558
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
