kind: Service
apiVersion: v1
metadata:
  name: example-akka-cluster
spec:
  type: NodePort
  selector:
    app: example-akka-cluster
  ports:
  - protocol: TCP
    name: management
    port: 8558
    targetPort: management
  - protocol: TCP
    name: api
    port: 8080
    targetPort: api
